# theme: minima
remote_theme: itszariep/Tessera
title: revelsix.ee
description: This is where I share cool stuff about my life
author: revelsix
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      image: /preview.jpg
